title: rails_table_for docs
email: roos.austin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation site for the rails_table_for gem
baseurl: "/rails_table_for" # the subpath of your site, e.g. /blog
url: "https://acroos.site" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  acroos

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
