name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install libsqlite3-dev
      run: sudo apt-get install -y libsqlite3-dev
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Rubocop
      run: bundle exec rake rubocop
    - name: Test
      run: bundle exec rake
